name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push FFmpeg Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./ffmpeg.Dockerfile
        push: true
        tags: cjgaspard/esp32-hls-ffmpeg:latest
        platforms: linux/amd64,linux/arm64

    - name: Docker Hub Description ffmpeg
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: cjgaspard/esp32-hls-ffmpeg
        readme-filepath: ./readme.md
        short-description: "ESP32-CAM ffmpeg Agent"
  
    # - name: Build and Push GStreamer Docker Image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./gstreamer.Dockerfile
    #     push: true
    #     tags: cjgaspard/esp32-hls-gstreamer:latest
    #     platforms: linux/amd64,linux/arm64

    # - name: Docker Hub Description gstreamer
    #   uses: peter-evans/dockerhub-description@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     repository: cjgaspard/esp32-hls-gstreamer
    #     readme-filepath: ./README.md
    #     short-description: "ESP32-CAM Agent"            
    
